# this code is partially generated by DeepSeek

import random
import time

def gen_array(array_size):
    array = []
    for index in range(array_size):
        array.append(random.randint(0, 1000))
    return array

def bubble_sort(arr):
    n = len(arr)
    last_swap = n - 1
    for i in range(n):
        swapped = False
        current_swap = 0
        for j in range(last_swap):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
                current_swap = j
        last_swap = current_swap
        if not swapped:
            break

if __name__ == "__main__":
    array1 = gen_array(10)
    array2 = gen_array(100)
    array3 = gen_array(1000)
    array4 = gen_array(100000)
    
    print("array1:")
    currentTime = time.time()
    bubble_sort(array1)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)
    
    print("array2:")
    currentTime = time.time()
    bubble_sort(array2)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)

    print("array3:")
    currentTime = time.time()
    bubble_sort(array3)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)
    
    print("array4:")
    currentTime = time.time()
    bubble_sort(array4)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)