# this code is partially generated by DeepSeek

import random
import time

def gen_array(array_size):
    array = []
    for index in range(array_size):
        array.append(random.randint(0, 1000))
    return array

def bubble_sort(arr):
    n = len(arr)
    left = 0
    right = n - 1
    while left < right:
        swapped = False
        # Forward pass (left to right)
        for i in range(left, right):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                swapped = True
                last_swap = i
        if not swapped:
            break
        right = last_swap
        # Backward pass (right to left)
        swapped = False
        for i in range(right, left, -1):
            if arr[i] < arr[i - 1]:
                arr[i], arr[i - 1] = arr[i - 1], arr[i]
                swapped = True
                last_swap = i
        if not swapped:
            break
        left = last_swap
    return arr

if __name__ == "__main__":
    array1 = gen_array(10)
    array2 = gen_array(100)
    array3 = gen_array(1000)
    array4 = gen_array(100000)
    
    print("array1:")
    currentTime = time.time()
    bubble_sort(array1)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)
    
    print("array2:")
    currentTime = time.time()
    bubble_sort(array2)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)

    print("array3:")
    currentTime = time.time()
    bubble_sort(array3)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)
    
    print("array4:")
    currentTime = time.time()
    bubble_sort(array4)
    currentTime = time.time() - currentTime
    print("time taken:", currentTime)
